export const AUTH_START = 'AUTH_START';
export const AUTH_END = 'AUTH_END';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGN_OUT = 'SIGN_OUT';
export const CLEAN_ERROR_MESSAGES = 'CLEAN_ERROR_MESSAGES';

export const POST_DICTIONARY_START = 'POST_DICTIONARY_START';
export const POST_DICTIONARY_SUCCESS = 'POST_DICTIONARY_SUCCESS';
export const POST_DICTIONARY_END = 'POST_DICTIONARY_END';
export const POST_DICTIONARY_FAIL = 'POST_DICTIONARY_FAIL';

export const DELETE_DICTIONARY_START = 'DELETE_DICTIONARY_START';
export const DELETE_DICTIONARY_SUCCESS = 'DELETE_DICTIONARY_SUCCESS';
export const DELETE_DICTIONARY_END = 'DELETE_DICTIONARY_END';
export const DELETE_DICTIONARY_FAIL = 'DELETE_DICTIONARY_FAIL';